# Generated by Django 5.1.6 on 2025-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_notification_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('post', 'Post')], max_length=10),
        ),
    ]
