# Generated by Django 5.1.6 on 2025-04-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_customizationitem_customization'),
        ('social', '0004_continent_country_city_worldposition'),
    ]

    operations = [
    ]
