# Generated by Django 5.1.6 on 2025-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_basecharacter_customization_base_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('post', 'Post'), ('world_position', 'World Position')], max_length=25),
        ),
    ]
