# Generated by Django 5.1.6 on 2025-04-12 07:58

import django.db.models.deletion
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDecorationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=social.models.city_decoration_image_path)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='social.city')),
            ],
        ),
    ]
