# Generated by Django 5.1.6 on 2025-04-15 10:31

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_citydecorationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainDecorationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=social.models.mountain_decoration_image_path)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
