# Generated by Django 5.1.6 on 2025-05-31 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_decorationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='introduction_characters/')),
                ('base_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduction_characters', to='social.basecharacter')),
            ],
        ),
    ]
