# Generated by Django 5.1.6 on 2025-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_introductioncharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
