# Generated by Django 5.1.6 on 2025-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_country_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='max_level',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
