from django.urls import path
from .views import (
    GCMDeviceCreateView,
    FollowersListView,
    FollowingListView,
    FollowCreateView,
    FollowDeleteView,
    PostCreateView,
    PostListView,
    LikePostView,
    UnlikePostView,
    CommentCreateView,
    CommentDeleteView,
    NotificationReadAllView,
    # WorldPositionView,
    # FollowingWorldPositionView,
    WorldPositionsListView,
    CustomizationItemListView,
    CustomizationItemByCategoryListView,
    CustomizationUpdateView,
    CustomizationView,
)

urlpatterns = [
    path('store-device-token/', GCMDeviceCreateView.as_view(), name='store_device_token'),
    path('followers/', FollowersListView.as_view(), name='followers'),
    path('following/', FollowingListView.as_view(), name='following'),
    path('follow/', FollowCreateView.as_view(), name='follow'),
    path('unfollow/<int:id>/', FollowDeleteView.as_view(), name='unfollow'),
    path('posts/', PostListView.as_view(), name='posts'),
    path('posts/<int:id>/like/', LikePostView.as_view(), name='like'),
    path('posts/<int:id>/unlike/', UnlikePostView.as_view(), name='unlike'),
    path('posts/create/', PostCreateView.as_view(), name='create_post'),
    path('posts/<int:id>/comment/', CommentCreateView.as_view(), name='comment'),
    path('comments/<int:id>/delete/', CommentDeleteView.as_view(), name='delete_comment'),
    path('notifications/read/all/', NotificationReadAllView.as_view(), name='read_all_notifications'),
    # path('get-my-position/', WorldPositionView.as_view(), name='get_my_position'),
    # path('get-following-positions/', FollowingWorldPositionView.as_view(), name='get_following_positions'),
    path("get-world-positions/", WorldPositionsListView.as_view(), name="get_world_positionq"),
    path("customization-items/", CustomizationItemListView.as_view(), name="customization_items"),
    path("customization-items/<str:category>/", CustomizationItemByCategoryListView.as_view(), name="customization_items_by_category"),
    path("update-customization/", CustomizationUpdateView.as_view(), name="update_customization"),
    path("customization/", CustomizationView.as_view(), name="customization"),
]
