# Generated by Django 5.1.1 on 2024-11-08 08:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1924, 12, 3)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2010, 11, 12))]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(250.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(250.0)]),
        ),
    ]
