# Generated by Django 5.1.1 on 2024-10-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_customuser_fitness_level_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='physical_particularities',
            field=models.TextField(blank=True),
        ),
    ]
