# Generated by Django 5.1.1 on 2025-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
