# Generated by Django 5.1.6 on 2025-04-15 09:34

import authentification.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_gameachievement_userachievement_userstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameachievement',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='progress',
        ),
        migrations.AddField(
            model_name='gameachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authentification.models.achievement_decoration_image_path),
        ),
        migrations.AddField(
            model_name='gameachievement',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameachievement',
            name='type',
            field=models.CharField(choices=[('reps', 'Reps'), ('workouts', 'Workouts'), ('level', 'Level'), ('duration', 'Duration'), ('calories', 'Calories'), ('active_days', 'Active Days'), ('pushups', 'Pushups'), ('squats', 'Squats'), ('pullups', 'Pullups'), ('jumping_jacks', 'Jumping Jacks')], default='reps', max_length=50),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='current_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_workout_date', models.DateTimeField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
