# Generated by Django 5.1.6 on 2025-04-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_remove_gameachievement_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='cities_finished',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
