# Generated by Django 5.1.6 on 2025-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_userprogress_cities_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
