# Generated by Django 5.1.6 on 2025-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_alter_userachievement_awarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='coins',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
