targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: fr
          input_directory: lib/i18n
          output_directory: lib/i18n
          use_device_locale: true
          fallback_strategy: base_locale
