targets:
  $default:
    builders:
      slang_builder:
        options:
          base_locale: fr
          input_directory: lib/i18n
          output_directory: lib/generated
          use_device_locale: true
          fallback_strategy: base_locale
