# Generated by Django 5.1.6 on 2025-04-12 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_remove_exercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
