# Generated by Django 5.1.6 on 2025-04-21 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_workoutsession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsessionexercise',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workoutsession'),
        ),
    ]
