# Generated by Django 5.1.6 on 2025-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_workoutsessionexercise_workout_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='transition_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
