default_platform(:ios)

platform :ios do
  private_lane :setup_asc_key do
    require 'base64'
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: Base64.decode64(ENV["ASC_P8_FILE"]),
      duration: 1200
    )
  end

  private_lane :build_ipa do
    setup_asc_key
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    latest = latest_testflight_build_number(app_identifier: app_id)
    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: latest + 1
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "Runner"
    )
    lane_context[SharedValues::IPA_OUTPUT_PATH]
  end

  desc "Distribute to TestFlight"
  lane :beta do
    ipa_path = build_ipa
    generic_notes = "Bug fixes and performance improvements"
    upload_to_testflight(
      ipa: ipa_path,
      changelog: generic_notes
    )
  end

  desc "Release to App Store"
  lane :release do
    ipa_path = build_ipa
    generic_notes = "Bug fixes and performance improvements"
    upload_to_app_store(
      ipa: ipa_path,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      release_notes: {
        "en-US" => generic_notes,
        "fr-FR" => generic_notes
      },
      submit_for_review: true,
      automatic_release: true,
      phased_release: false
    )
  end
end
