require 'base64'

default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: Base64.decode64(ENV["ASC_API_KEY_BASE64"]),
      is_key_content_base64: false
    )
    pilot(
      api_key: api_key,
      # From ios/ dir, the ipa is at ../build/ios/ipa
      ipa: Dir["../build/ios/ipa/*.ipa"].first,
      skip_waiting_for_build_processing: false
    )
  end

  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: Base64.decode64(ENV["ASC_API_KEY_BASE64"]),
      is_key_content_base64: false
    )
    deliver(
      api_key: api_key,
      # From ios/ dir, the ipa is at ../build/ios/ipa
      ipa: Dir["../build/ios/ipa/*.ipa"].first,
      submit_for_review: false, # set true if you want auto-submit
      automatic_release: false   # set true to auto release on approval
    )
  end
end
