name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: integration-tests
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}

  integration-tests:
    needs: lint
    uses: ./.github/workflows/integration_tests.yml
    with:
      ref: ${{ github.ref }}
