name: Flutter Test Pipeline

on:
    workflow_call:
        inputs:
            ref:
                description: 'The git reference to run Flutter tests on'
                required: true
                type: string
        secrets:
            FLUTTER_GOOGLE_SERVICES:
                description: 'Base64 encoded Google Services credentials JSON for Flutter'
                required: true
            FLUTTER_GOOGLE_CLIENT_ID:
                description: 'Google Client ID for Flutter'
                required: true

jobs:
    flutter_tests:
        name: Run Flutter tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.29.0
                channel: stable
            - name: Install dependencies
              run: flutter pub get
              working-directory: ./playfit-mobile/playfit
            - name: Decode Google Services credentials
              run: echo "${{ secrets.FLUTTER_GOOGLE_SERVICES }}" | base64 --decode > android/app/google-services.json
              working-directory: ./playfit-mobile/playfit
            - name: Set up environment variables
              run: |
                echo "SERVER_BASE_URL=http://${{ vars.FLUTTER_SERVER_IP }}:${{ vars.FLUTTER_SERVER_PORT }}" >> .env
                echo "SERVER_BASE_WS_URL=ws://${{ vars.FLUTTER_SERVER_IP }}:${{ vars.FLUTTER_SERVER_PORT }}" >> .env
                echo "GOOGLE_CLIENT_ID=${{ secrets.FLUTTER_GOOGLE_CLIENT_ID }}" >> .env
              working-directory: ./playfit-mobile/playfit
            - name: Run tests
              run: flutter test
              working-directory: ./playfit-mobile/playfit