name: Integration tests

on:
  workflow_call:
    inputs:
      ref:
        description: 'The git reference to run integration tests on'
        required: true
        type: string

jobs:
    django_tests:
        name: Run Django tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11
            - name: Install dependencies
              run: pip install -r requirements.txt
              working-directory: ./backend
            - name: Run tests
              run: python manage.py test
              working-directory: ./backend/playfit

    flutter_tests:
        name: Run Flutter tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.19.0
            - name: Install dependencies
              run: flutter pub get
              working-directory: ./playfit-mobile/playfit
            - name: Run tests
              run: flutter test
              working-directory: ./playfit-mobile/playfit
