name: Lint code

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint_python:
    name: Lint Python code with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
