name: Pipeline on main branch

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  integration-tests:
    needs: lint
    uses: ./.github/workflows/integration_tests.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_CRYPTOGRAPHY_KEY: ${{ secrets.DJANGO_CRYPTOGRAPHY_KEY }}
      DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
      DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
      DJANGO_FCM_API_KEY: ${{ secrets.DJANGO_FCM_API_KEY }}
      DJANGO_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DJANGO_GOOGLE_APPLICATION_CREDENTIALS }}
      FLUTTER_GOOGLE_SERVICES: ${{ secrets.FLUTTER_GOOGLE_SERVICES }}
      FLUTTER_GOOGLE_CLIENT_ID: ${{ secrets.FLUTTER_GOOGLE_CLIENT_ID }}

  build:
    needs: integration-tests
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      FLUTTER_GOOGLE_SERVICES: ${{ secrets.FLUTTER_GOOGLE_SERVICES }}
      FLUTTER_GOOGLE_CLIENT_ID: ${{ secrets.FLUTTER_GOOGLE_CLIENT_ID }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      GH_PAT: ${{ secrets.GH_PAT }}
  
  mirror-to-epitech:
    name: Mirror to Epitech
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.EPITECH_REPO_URL }}
          ssh_private_key: ${{ secrets.EPITECH_MIRROR_KEY }}
