name: Pipeline on main branch (PR)
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  integration-tests:
    needs: lint
    uses: ./.github/workflows/integration_tests.yml
    with:
      ref: ${{ github.head_ref }}
    secrets:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_CRYPTOGRAPHY_KEY: ${{ secrets.DJANGO_CRYPTOGRAPHY_KEY }}
      DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
      DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
      DJANGO_FCM_API_KEY: ${{ secrets.DJANGO_FCM_API_KEY }}
      DJANGO_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DJANGO_GOOGLE_APPLICATION_CREDENTIALS }}
      FLUTTER_GOOGLE_SERVICES: ${{ secrets.FLUTTER_GOOGLE_SERVICES }}
      FLUTTER_GOOGLE_CLIENT_ID: ${{ secrets.FLUTTER_GOOGLE_CLIENT_ID }}