name: Test Pipeline

on:
    - push

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            ref: ${{ github.ref }}
        secrets:
            FLUTTER_GOOGLE_SERVICES: ${{ secrets.FLUTTER_GOOGLE_SERVICES }}
            FLUTTER_GOOGLE_CLIENT_ID: ${{ secrets.FLUTTER_GOOGLE_CLIENT_ID }}
            KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
            KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            GH_PAT: ${{ secrets.GH_PAT }}